<?php

return [

    'PULGAS' => 'PULGAS',
    'GARRAPATAS' => 'GARRAPATAS',
    'PIOJOS' => 'PRUITO',
    'COPRO DIRECTO' => 'COPRO DIRECTO',
    'COPRO FLOTACIÓN' => 'COPRO FLOTACIÓN',
    'RASPADO' => 'RASPADO',
    'CITOLOGIA' => 'CITOLOGIA',
    'RX 1/2 CONTRASTE' => 'RX 1/2 CONTRASTE',
    'GEO' => 'GEO',
    'PERFIL RENAL' => 'PERFIL RENAL',
    'QUÍMICA SANGUÍNEA' => 'QUÍMICA SANGUÍNEA',
    'PERFIL PREANESTÉSICO' => 'PERFIL PREANESTÉSICO',
    'PERFIL HEPÁTICO' => 'PERFIL HEPÁTICO',
    'SNAP' => 'SNAP',
    'ECOSONOGRAMA' => 'ECOSONOGRAMA',
    'RADIOGRAFIA' => 'RADIOGRAFIA',
    'ENDOSCOPIA' => 'ENDOSCOPIA',
    'HOSPITALIZACIÓN' => 'HOSPITALIZACIÓN',
    'SEDACIÓN' => 'SEDACIÓN',
    'ANESTESIA' => 'ANESTESIA',
    'SUTURAS' => 'SUTURAS',
    'ELECTROLITOS' => 'ELECTROLITOS',
    'OBSERACIÓN' => 'OBSERACIÓN',
    'INTERCONSULTA' => 'INTERCONSULTA',
   

];
